apiVersion: v2
name: observability
description: A Helm chart for observability (Prometheus, Grafana, Alertmanager)
type: application
version: 81.6.9
appVersion: "v0.87.1"

dependencies:
  - name: kube-prometheus-stack
    version: 81.6.9
    repository: https://prometheus-community.github.io/helm-charts
  - name: alloy
    version: 1.5.1
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.24.1
    repository: https://grafana.github.io/helm-charts
