apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: git@github.com:mien-lab/k8s-starter-pack.git
      path: manifests/cluster/overlays/local
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
