apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/external-secrets/external-secrets
      path: deploy/crds
      targetRevision: v2.0.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
