apiVersion: v2
name: kyverno
description: A Helm chart for Kyverno policy engine
type: application
version: 3.7.1
appVersion: "v1.17.1"

dependencies:
  - name: kyverno
    version: 3.7.1
    repository: https://kyverno.github.io/kyverno/
