kyverno:
  admissionController:
    replicas: 1
    container:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 384Mi
    initContainer:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 256Mi
    serviceMonitor:
      enabled: true

  backgroundController:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi

  cleanupController:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi

  reportsController:
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
