apiVersion: v2
name: argocd
description: Argo CD - declarative GitOps continuous delivery for Kubernetes
type: application
version: 0.1.0
appVersion: "v3.3.0"
kubeVersion: ">=1.25.0-0"

dependencies:
  - name: argo-cd
    version: 9.4.1
    repository: https://argoproj.github.io/argo-helm
